env:
  global:
        - CI_NODE_TOTAL=1
        - REPO_DIR=kProcessor
        - TRAVIS_DEBUG_MODE=true
        - BUILD_COMMIT=master
        - BUILD_DEPENDS=""
        - TEST_DEPENDS="pytest"
        - PLAT=x86_64
        - UNICODE_WIDTH=32
        - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
language:        cpp
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python:          3.6
sudo:            required
dist:            trusty
services:        docker

matrix:
  include:
    - os: linux
      sudo: required
      env:
        - MB_PYTHON_VERSION=3.6
        - MB_ML_VER=2014

    - os: linux
      sudo: required
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_ML_VER=2014
    
    - os: linux
      sudo: required
      env:
        - MB_PYTHON_VERSION=3.8
        - MB_ML_VER=2014


before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
  - echo "Sending wheels .."

deploy:
  provider: bintray
  file: "descriptor.json"
  user: "mr-eyes"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true
